/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115441-g510494760c-20240529"
#endif /* AVUTIL_FFVERSION_H */
